spring:
  application:
    name: AIPlatform
  thymeleaf:
    cache: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
report:
  font:
    path: static/font/NanumBarunGothic.ttf